#!/bin/bash

URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT="data.json"
ERROR_FILE="errors.txt"


# Make API request silently and save HTTP status
status_code=$(curl -s -w "%{http_code}" -o "$OUTPUT" "$URL")

curl -o data.json https://pokeapi.co/api/v2/pokemon/pikachu

#Check if request was successfu (status code 200)

if [ "$status_code" -eq 200 ]
    then
        echo "Request successful! Data saved to $OUTPUT"
else
    echo "Request failed with status code $status_code" >> "$ERROR_FILE"
    echo "Request failed! See $ERROR_FILE for details."

fi