#!/bin/bash

#path to data file
DATA_FILE="data.json"

if [ ! -f "$DATA_FILE" ]
then
    echo "Error:$DATA_FILE not found"
    exit 1
fi

#Extacht data using jq
name=$(jq -r '.name' "$DATA_FILE")
formatted_height=$(jq -r '.height' "$DATA_FILE")
formatted_weight=$(jq -r '.weight' "$DATA_FILE")
type=$(jq -r '.types[0].type.name' "$DATA_FILE")


echo "${name^} is of type ${type^}, weights ${formatted_height}kg, and is ${formatted_weight}m tall"