#!/bin/bash

#path to data file
DATA_FILE="data.json"

if [ ! -f "$DATA_FILE" ]
then
    echo "Error:$DATA_FILE not found"
    exit 1
fi

#Extacht data using jq
NAME=$(jq -r '.name' "$DATA_FILE")
HEIGHT=$(jq -r '.height' "$DATA_FILE")
WEIGHT=$(jq -r '.weight' "$DATA_FILE")
TYPE=$(jq -r '.types[0].type.name' "$DATA_FILE")

# echo $HEIGHT
# Convert decimeters -> meters and hectograms -> kilograms using awk
formatted_height=$(echo "$HEIGHT" | awk '{printf "%.f", $1 /10}')
formatted_weight=$(echo "$WEIGHT" | awk '{printf "%.f", $1 /10}')


#Capitalize first letter using sed 
name=$(echo "$NAME" | sed 's/.*/\u&/')
type=$(echo "$TYPE" | sed 's/.*/\u&/')

# Print formatted sentence
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."